apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalelite.fullname" . }}-nginx
  labels:
    {{- include "scalelite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scalelite.nginxSelectorLabels" . | nindent 4 }}
