apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recordings-pvc
spec:
  accessModes:
    - {{- include "scalelite.pvcAccessMode" . }}
  storageClassName: {{- include "scalelite.pvcStorageClass" . }}
  resources:
    requests:
      storage: 250Gi
