apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recordings-pvc
spec:
  accessModes:
    - {{ .Values.pvcAccessMode }}
  storageClassName: {{ .Values.pvcStorageClass }}
  resources:
    requests:
      storage: 250Gi
